### PR TITLE
prepare for CRAN update

### PR DESCRIPTION
**Pull request by MattCowgill**

### CODE REVIEW

**Comment by MattCowgill** [comment]
FYI @oscarlane, I have submitted an update to CRAN incorporating the new internet check; I expect this will be on CRAN within a few days

**Comment by OscarLane** [comment]
Thats great news Matt, thanks for taking the time to make the submission!

**Comment by MattCowgill** [comment]
No worries. The new version is up now on CRAN in source form; the built binaries will appear over the next few days. Thanks again for highlighting this issue + proposing the fix

**Comment by OscarLane** [comment]
I just checked CRAN and it looks like it's already been updated, speedy!

**Comment by OscarLane** [comment]
OK thanks for pointing out, yes I can't compile binaries in this environment so will sit tight.

**Pull request merged**
