### PR TITLE
Add support for bespoke MRM formatting in `read_lfs_datacube`

### PR DESCRIPTION
**Pull request by angusmoore**
New MRM datacube has a new and exciting format. This adds custom parsing logic for those tables, by adding an if-then in `read_lfs_datacube` to detect MRM and dump out to separate parsing logic.

Closes this tweet: https://x.com/MattCowgill/status/1806467970740486518

Thoughts/changes on returned dataframe structure of course welcome.

### CODE REVIEW

**Comment by MattCowgill** [comment]
@angusmoore you absolute legend! Sorry it's taken me a while to get to this

**Comment by angusmoore** [comment]
No problem at all, happy to help! test failures look unrelated? Tests were passing locally (`devtools::check()`) when I pushed, but seem to be failing now on a test about the job mobility datacube (some new and exciting format change there too perhaps...)

**Comment by MattCowgill** [comment]
sorry for the radio silence @angusmoore  - I'll fix this up

**Comment by angusmoore** [comment]
No problem at all!

**Comment by MattCowgill** [comment]
Merging this now @angusmoore. I fixed the (unrelated) problems that were causing tests to fail, and added you as a contributor in DESCRIPTION

**Pull request merged**
