### PR TITLE
Download data cube

### PR DESCRIPTION
**Pull request by daviddiviny**
This addresses #74 .

### CODE REVIEW

**Comment by daviddiviny** [comment]
@MattCowgill I think this is ready for your review.

**Comment by MattCowgill** [comment]
Thanks @daviddiviny, will review ASAP

**Comment by MattCowgill** [comment]
Hi @daviddiviny this looks really good, thank you. 

When I run the example though, nothing happens. Nothing is returned, no error or warning thrown. 

``` r
library(readabs)
#> Environment variable 'R_READABS_PATH' is unset. Downloaded files will be saved in a temporary directory.
#> You can set 'R_READABS_PATH' at any time. To set it for the rest of this session, use
#>  Sys.setenv(R_READABS_PATH = <path>)

readabs::download_abs_data_cube(cat_no = "6291.0.55.003",
                       cube = "EQ09") 
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Can you please help me figure out what's going on there? 

Also: could you please add a unit test(s) (`usethis::use_test()`) of the new function?

Thanks

**Comment by daviddiviny** [comment]
Is there a file downloaded?

**Comment by MattCowgill** [comment]
yes! Sorry, I missed that. I'll approve the PR and add a unit test(s). Thanks again for your work on this

**Comment by daviddiviny** [comment]
Do you think it needs a message telling people where the file is saved? Also, do you need any documentation for the vignette?

**Comment by MattCowgill** [comment]
Hi @daviddiviny, yes I think a message with the file path would be good. It should return `invisible(TRUE)` as well I think. A few unit tests would also be handy, but I can add those if you like. Thanks again for your work on this -- I've accepted the PR, so let me know if you plan to add to this

**Pull request merged**
