### PR TITLE
Draft: Increase code coverage

### LINKED ISSUE #252: Increasing code coverage
To enhance testing code coverage of master branch closer to 100%.

Priority files:
- [ ] search_files.R
- [ ] check_abs_connection.R
- [ ] read_payrolls.R
- [ ] search_catalogues.R
- [ ] read_abs_local.R

image

### PR DESCRIPTION
**Pull request by smishr**
This PR resolves #252 

- [ ] search_files.R
- [ ] check_abs_connection.R
- [ ] read_payrolls.R
- [ ] search_catalogues.R
- [ ] read_abs_local.R

### CODE REVIEW

**Comment by MattCowgill** [comment]
Hi @smishr thanks for this! This is still in draft, right?

**Comment by smishr** [comment]
Yep in draft, as i get time over next few weeks ill continue

**Comment by MattCowgill** [comment]
Hi, I'm planning to close this FYI. Please let me know if you'd like to keep it open.

**Comment by MattCowgill** [comment]
Closing as per above, as this appears to be a dormant PR

**Pull request closed without merging**
