### PR TITLE
Initial commit towards #49

### PR DESCRIPTION
**Pull request by HughParsonage**
Here is the initial commit of the fst-cache idea raised in #49 . 

Somethings I'm unsure about:

  1. What sort of metadata should be stored alongside the `fst` files? Currently, I've got a `.dcf` which seems to be normal for this sort of thing. I'm currently storing the MD5 and 'ProductReleaseDate' but both of these are currently not used for any purpose.
  2. Should the `fst` directory be a subset of `path` or of `path/cat_no`? Perhaps this doesn't matter (it may not even matter if we choose to change it). 
  3. General ergonomics. I've tested this out on "6202.0" and "6345.0" but I'm not sure how the package is actually being used out there so not sure if these are representative enough.

Note the build failure is a technical one. I will fix.

### CODE REVIEW

**Comment by MattCowgill** [comment]
Thanks @HughParsonage. This looks good, but there's a lot to ponder and I'm not going to have a chance to properly review it today (parent life). I'll review as soon as I can

**Comment by MattCowgill** [comment]
hi @HughParsonage sorry for the delay - I'll properly review this today

FYI I'm going to send the current `master` to CRAN as a minor version update. I want to have a release with your `path` argument change, before we make further changes with the `.fst` cache etc.

**Comment by MattCowgill** [comment]
Hi Hugh,
This looks great, thank you. 

Some comments / questions:

1. Do we need to add the `hutils` dependency? 
2. What's the reason to check for the presence of the `fst` package in the `read_abs()` function (with `requireNamespace("fst", quietly = TRUE)`) rather than just including it in Imports in DESCRIPTION?
3. I am contemplating deprecating the `metadata` argument of `read_abs()` - views on this appreciated
4. I'm not sure I understand the method for checking whether the cached .fst data is up-to-date
5. We should add an argument to `read_abs()` - something like `check_local`, which would be TRUE by default. If FALSE, `read_abs()` should download the relevant ABS spreadsheet(s) regardless of the fst cache

**Comment by MattCowgill** [comment]
re: 2, this is a genuine question - I see this is in WRE at 1.1.3.1

**Comment by HughParsonage** [comment]
> 1. Do we need to add the hutils dependency?

Kinda. It's used for `provide.file()` and `provide.dir()` which were both pretty important and I found were a bit more tricky to implement than I initially thought. It's lightweight.

> What's the reason to check for the presence of the fst package in the read_abs() function (with requireNamespace("fst", quietly = TRUE)) rather than just including it in Imports in DESCRIPTION?

Two weak reasons: (a) I see this enhancement as outside the core of the package -- the package can function just fine without the `fst` package. (b) because the `fst` write occurs after the (potentially lengthy) download, it would be bad UX if the function were to fail at that time, so I try to make extra sure `fst` will work.

> I'm not sure I understand the method for checking whether the cached .fst data is up-to-date

There is none at this time.

> We should add an argument to read_abs() - something like check_local, which would be TRUE by default. If FALSE, read_abs() should download the relevant ABS spreadsheet(s) regardless of the fst cache.

Yes.

**Comment by MattCowgill** [comment]
Hi @HughParsonage, that all sounds good to me, thanks

**Comment by HughParsonage** [comment]
Thanks I'll try to get this finished by Wednesday. Want to give it a once over at least before then.

**Comment by MattCowgill** [comment]
Hi @HughParsonage - this PR is marked as a work in progress - is that right?

**Comment by HughParsonage** [comment]
Whoops. I must have forgotten to mark it ready.

It’s ready.

**Comment by MattCowgill** [comment]
This is great @HughParsonage. One thing I don't understand: why only write the `.fst` file when `tables == "all"`? 

Is there a reason why `catno2fst()` could not also take a `tables` argument and construct a filename of the form catno_tables, like `6202-0_all.fst` or `6202-0_1.fst`? Maybe I'm missing something...

**Comment by HughParsonage** [comment]
No technical reason, but the first priority was to make sure read_abs()
returned the correct result whether retrieving from fst or not. Ultimately,
the "tables" partition seems to be a 'back-end' issue, rather than a direct
map to a particular ABS series. If someone does read_abs("6401.0", tables =
1) and then runs read_abs("6401.0"), we need to make sure the initial write
doesn't exclude tables > 1.

It would be good to know why people use the tables argument (apart from
performance or internet connection issues).

**Comment by MattCowgill** [comment]
I generally use the `tables` argument for two reasons:

1) it’s quicker (download time for `tables = all` for some catalogue numbers can be intolerably long)
2) it’s easier to work with the data from an individual table, because the ‘series’ column will split into categories that make sense.

I’m happy to merge this PR and will continue thinking about this.

**Pull request merged**
